# Generated by Django 4.2 on 2023-07-07 04:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_image')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('phone_number_1', models.CharField(max_length=16)),
                ('phone_number_2', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number_3', models.CharField(blank=True, max_length=16, null=True)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_media_1', models.URLField(blank=True, null=True)),
                ('social_media_2', models.URLField(blank=True, null=True)),
                ('social_media_3', models.URLField(blank=True, null=True)),
                ('social_media_4', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('site_link', models.URLField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
            options={
                'verbose_name': 'CompanyGallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('tag', models.CharField(blank=True, choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('premium', 'Премиум')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
        ),
    ]
