# Generated by Django 4.2 on 2023-07-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='aboutus/obi.jpg', upload_to='aboutus/', verbose_name='image')),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('instagram', models.URLField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
